server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    gzip on;
    gzip_types application/javascript application/json text/css;

    location / {
        add_header Access-Control-Allow-Origin *;
        try_files $uri $uri/ =404;
    }
}
